### ISSUE TITLE
IMCD_LZW_TABLE_TOO_SMALL exception with large image

### ISSUE THREAD

**Issue by AAAdaisy** [cgohlke/imagecodecs#121]
![屏幕截图 2024-12-06 093232](https://github.com/user-attachments/assets/7723c7a6-74a8-457e-b5f8-7fbb6677cb3c)
Hi,
I'm not sure if I should raise the issue here, since I encountered this error in terminal when stitching FOV images in napari-cosmx, and for the first several markers everything was right, until stitching FOV056 of Membrane marker. I'm not sure if it is due to the broken file or some other reason.
```
(napari) zq@bld:~$ stitch-images 
-i "/mnt/0_nas/XXX/XXXprotein_RawFile/YKKY0242_rawImgS1/23R63134988SLZA/20240109_082633_S2/CellStatsDir" 
-f "/mnt/0_nas/XXX/XXXprotein_RawFile/YKKY0242_rawImgS1/23R63134988SLZA/20240109_082633_S2/RunSummary" 
-o "/home/zq/XXXXprogram/data/XXXdata/Napari/napari_output"                       
                                                                                           
Using legacy format to read FOVs                                                                                                          
Reading pixel size and magnification from metadata... scale = 0.1203 um/px
Stitching cell segmentation labels.
Added FOV 274/274|█████████████████|100%
Writing labels multiscale output to zarr.
Writing level 1 of 9, shape: (142411, 95919), chunksize: (8192, 8192)
Writing level 2 of 9, shape: (71205, 47959), chunksize: (4096, 4096)
Writing level 3 of 9, shape: (35602, 23979), chunksize: (2048, 2048)
Writing level 4 of 9, shape: (17801, 11989), chunksize: (1024, 1024)
Writing level 5 of 9, shape: (8900, 5994), chunksize: (512, 512)
Writing level 6 of 9, shape: (4450, 2997), chunksize: (256, 256)
Writing level 7 of 9, shape: (2225, 1498), chunksize: (128, 128)
Writing level 8 of 9, shape: (1112, 749), chunksize: (64, 64)
Writing level 9 of 9, shape: (556, 374), chunksize: (32, 32)
Saving metadata
Stitching images for PanCK.
Added FOV 274/274|█████████████████|100%
Writing PanCK multiscale output to zarr.
Writing level 1 of 9, shape: (142411, 95919), chunksize: (8192, 8192)
Writing level 2 of 9, shape: (71205, 47959), chunksize: (4096, 4096)
Writing level 3 of 9, shape: (35602, 23979), chunksize: (2048, 2048)
Writing level 4 of 9, shape: (17801, 11989), chunksize: (1024, 1024)
Writing level 5 of 9, shape: (8900, 5994), chunksize: (512, 512)
Writing level 6 of 9, shape: (4450, 2997), chunksize: (256, 256)
Writing level 7 of 9, shape: (2225, 1498), chunksize: (128, 128)
Writing level 8 of 9, shape: (1112, 749), chunksize: (64, 64)
Writing level 9 of 9, shape: (556, 374), chunksize: (32, 32)
Calculating contrast limits
Writing omero metadata...
{'min': 0, 'max': 1108, 'start': 19, 'end': 995}
Stitching images for CD3.
Added FOV 274/274|█████████████████|100%
Writing CD3 multiscale output to zarr.
Writing level 1 of 9, shape: (142411, 95919), chunksize: (8192, 8192)
Writing level 2 of 9, shape: (71205, 47959), chunksize: (4096, 4096)
Writing level 3 of 9, shape: (35602, 23979), chunksize: (2048, 2048)
Writing level 4 of 9, shape: (17801, 11989), chunksize: (1024, 1024)
Writing level 5 of 9, shape: (8900, 5994), chunksize: (512, 512)
Writing level 6 of 9, shape: (4450, 2997), chunksize: (256, 256)
Writing level 7 of 9, shape: (2225, 1498), chunksize: (128, 128)
Writing level 8 of 9, shape: (1112, 749), chunksize: (64, 64)
Writing level 9 of 9, shape: (556, 374), chunksize: (32, 32)
Calculating contrast limits
Writing omero metadata...
{'min': 0, 'max': 1348, 'start': 17, 'end': 1221}
Stitching images for Membrane.
Added FOV 56/274|███▋              | 20%
Traceback (most recent call last):
  File "/home/zq/.conda/envs/napari/bin/stitch-images", line 8, in <module>
    sys.exit(main())
  File "/home/zq/.conda/envs/napari/lib/python3.9/site-packages/napari_cosmx/utils/stitch_images.py", line 167, in main
    tile = my_tiff.pages[i].asarray()
  File "/home/zq/.conda/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 9444, in asarray
    for _ in self.segments(
  File "/home/zq/.conda/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 9240, in segments
    yield decode(segment)
  File "/home/zq/.conda/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 9227, in decode
    return func(decode(*args, **decodeargs))  # type: ignore
  File "/home/zq/.conda/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 9152, in decode_other
    data = decompress(data, out=size * dtype.itemsize)
  File "imagecodecs/_imcd.pyx", line 1435, in imagecodecs._imcd.lzw_decode
imagecodecs._imcd.ImcdError: imcd_lzw_decode returned IMCD_LZW_TABLE_TOO_SMALL
```

Environment 
Python 3.9.20 
imagecodecs            2024.9.22
tifffile                        2020.6.3
dask                          2024.8.0
dask-image               2024.5.3
imagecodecs             2024.9.22
imagecodecs-lite       2019.12.3
imageio                     2.36.1
imagesize                  1.4.1
importlib_metadata   8.5.0
ome-types                 0.5.3
napari-CosMx            0.4.17.1

**Comment by cgohlke** [comment]
Can you share the TIFF file please to reproduce the issue?

**Comment by cgohlke** [comment]
Cannot reproduce.
