### ISSUE TITLE
Not able to install this module

### ISSUE THREAD

**Issue by AnamikaPandey7522** [cgohlke/imagecodecs#96]
Collecting imagecodecs==2020.5.30
  Using cached imagecodecs-2020.5.30.tar.gz (9.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running egg_info
      creating C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info
      writing C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info\PKG-INFO
      writing dependency_links to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info\dependency_links.txt
      writing entry points to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info\entry_points.txt
      writing requirements to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info\requires.txt
      writing top-level names to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info\top_level.txt
      writing manifest file 'C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-rh2fh8uk\imagecodecs.egg-info\SOURCES.txt'
      [1/1] Cythonizing imagecodecs/_aec.pyx
      [1/1] Cythonizing imagecodecs/_bitshuffle.pyx
      [1/1] Cythonizing imagecodecs/_blosc.pyx
      [1/1] Cythonizing imagecodecs/_brotli.pyx
      [1/1] Cythonizing imagecodecs/_bz2.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

                  memgif.data = <GifByteType*>&dst[0]
                  memgif.size = dstsize
                  memgif.offset = 0

                  gif = EGifOpen(<void*>&memgif, gif_output_func, &err)
                                                 ^
      ------------------------------------------------------------

      imagecodecs\_gif.pyx:164:43: Cannot assign type 'int (GifFileType *, const GifByteType *, int) except? -1 nogil' to 'OutputFunc'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (GifFileType *, const GifByteType *, int) except? -1 nogil'.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  memgif.data = <GifByteType*>&src[0]
                  memgif.size = srcsize
                  memgif.offset = 0
                  memgif.owner = 0

                  gif = DGifOpen(<void*>&memgif, gif_input_func, &err)
                                                 ^
      ------------------------------------------------------------

      imagecodecs\_gif.pyx:246:43: Cannot assign type 'int (GifFileType *, GifByteType *, int) except? -1 nogil' to 'InputFunc'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (GifFileType *, GifByteType *, int) except? -1 nogil'.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Acer\AppData\Local\Temp\pip-install-vm5atdc3\imagecodecs_fdd22b472980435fbb14cb1d5ecb1991\setup.py", line 404, in <module>
          setup(
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "C:\Users\Acer\AppData\Local\Temp\pip-install-vm5atdc3\imagecodecs_fdd22b472980435fbb14cb1d5ecb1991\setup.py", line 380, in finalize_options
          cythonize(
        File "C:\Users\Acer\anaconda3\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: imagecodecs/_gif.pyx
      [1/1] Cythonizing imagecodecs/_gif.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(base) C:\Users\Acer>pip install --upgrade imagecodecs
Requirement already satisfied: imagecodecs in c:\users\acer\anaconda3\lib\site-packages (2023.1.23)
Collecting imagecodecs
  Obtaining dependency information for imagecodecs from https://files.pythonhosted.org/packages/2c/01/03c0409e8a2cd99b220d95779d658d9f487318d5191805f86cf29d683257/imagecodecs-2024.1.1-cp311-cp311-win_amd64.whl.metadata
  Downloading imagecodecs-2024.1.1-cp311-cp311-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: numpy in c:\users\acer\anaconda3\lib\site-packages (from imagecodecs) (1.24.3)
Downloading imagecodecs-2024.1.1-cp311-cp311-win_amd64.whl (25.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.4/25.4 MB 7.6 MB/s eta 0:00:00
Installing collected packages: imagecodecs
  Attempting uninstall: imagecodecs
    Found existing installation: imagecodecs 2023.1.23
    Uninstalling imagecodecs-2023.1.23:
      Successfully uninstalled imagecodecs-2023.1.23
Successfully installed imagecodecs-2024.1.1

(base) C:\Users\Acer>pip install apeer_ometiff_library
Collecting apeer_ometiff_library
  Using cached apeer_ometiff_library-1.10.1-py3-none-any.whl (19 kB)
Requirement already satisfied: numpy>=1.18.5 in c:\users\acer\anaconda3\lib\site-packages (from apeer_ometiff_library) (1.24.3)
Collecting tifffile==2020.6.3 (from apeer_ometiff_library)
  Using cached tifffile-2020.6.3-py3-none-any.whl (133 kB)
Collecting imagecodecs==2020.5.30 (from apeer_ometiff_library)
  Using cached imagecodecs-2020.5.30.tar.gz (9.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running egg_info
      creating C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info
      writing C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info\PKG-INFO
      writing dependency_links to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info\dependency_links.txt
      writing entry points to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info\entry_points.txt
      writing requirements to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info\requires.txt
      writing top-level names to C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info\top_level.txt
      writing manifest file 'C:\Users\Acer\AppData\Local\Temp\pip-pip-egg-info-ou29vsl0\imagecodecs.egg-info\SOURCES.txt'
      [1/1] Cythonizing imagecodecs/_aec.pyx
      [1/1] Cythonizing imagecodecs/_bitshuffle.pyx
      [1/1] Cythonizing imagecodecs/_blosc.pyx
      [1/1] Cythonizing imagecodecs/_brotli.pyx
      [1/1] Cythonizing imagecodecs/_bz2.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...

                  memgif.data = <GifByteType*>&dst[0]
                  memgif.size = dstsize
                  memgif.offset = 0

                  gif = EGifOpen(<void*>&memgif, gif_output_func, &err)
                                                 ^
      ------------------------------------------------------------

      imagecodecs\_gif.pyx:164:43: Cannot assign type 'int (GifFileType *, const GifByteType *, int) except? -1 nogil' to 'OutputFunc'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (GifFileType *, const GifByteType *, int) except? -1 nogil'.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  memgif.data = <GifByteType*>&src[0]
                  memgif.size = srcsize
                  memgif.offset = 0
                  memgif.owner = 0

                  gif = DGifOpen(<void*>&memgif, gif_input_func, &err)
                                                 ^
      ------------------------------------------------------------

      imagecodecs\_gif.pyx:246:43: Cannot assign type 'int (GifFileType *, GifByteType *, int) except? -1 nogil' to 'InputFunc'. Exception values are incompatible. Suggest adding 'noexcept' to type 'int (GifFileType *, GifByteType *, int) except? -1 nogil'.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Acer\AppData\Local\Temp\pip-install-msvjv3mr\imagecodecs_cb39dd6e8cf843f7a0edc5efe1579aa4\setup.py", line 404, in <module>
          setup(
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\Acer\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "C:\Users\Acer\AppData\Local\Temp\pip-install-msvjv3mr\imagecodecs_cb39dd6e8cf843f7a0edc5efe1579aa4\setup.py", line 380, in finalize_options
          cythonize(
        File "C:\Users\Acer\anaconda3\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\Acer\anaconda3\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: imagecodecs/_gif.pyx
      [1/1] Cythonizing imagecodecs/_gif.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

this is the Whole error I'm getting. Please resolve it

**Comment by cgohlke** [comment]
It's an issue with the [apeer-ometiff-library](https://github.com/apeer-micro/apeer-ometiff-library). Downgrade your Python version and/or open an issue there.
